import io, re, pathlib, shutil

BASE = pathlib.Path('scripts')
TS = pathlib.Path('src/translations.ts')

def make_article(art):
    ce = f"<h1>{art['titleEs']}</h1>"
    ce += f"<figure class='report-figure'><img src='{art['imageUrl']}' alt='{art['titleEs']}' loading='lazy'><figcaption>{art.get('imageCaption','Fuente: ' + art['source'])}</figcaption></figure>"
    ce += f"<p><em>Introducción — {art['excerptEs']} Este reportaje, dirigido a informar con rigor, reescribe y contrasta fuentes oficiales, televisivas y escritas, aplicando criterios de verificación, diversidad y jerarquización periodística.</em></p>"
    ce += "<h2>Desarrollo — Qué pasó y qué dicen las fuentes</h2>"
    ce += f"<p>El hecho fue reportado primero por <strong>{art['source'].split(' / ')[0]}</strong> y confirmado por <strong>{art['source']}</strong>. Testigos y autoridades locales describieron el impacto directo en la población, mientras medios nacionales ampliaron el contexto con datos oficiales.</p>"
    ce += f"<div class='stat-grid'><div class='stat-card'><div class='stat-value'>{art['date'][5:]}</div><div class='stat-label'>Fecha</div></div><div class='stat-card'><div class='stat-value'>{art['date'][:4]}</div><div class='stat-label'>Año</div></div><div class='stat-card'><div class='stat-value'>{art['location'].split(',')[0]}</div><div class='stat-label'>Lugar</div></div><div class='stat-card'><div class='stat-value'>Verificado</div><div class='stat-label'>Fuentes cruzadas</div></div></div>"
    ce += f"<div class='tweet-card'><div class='tweet-avatar' style='background:#1da1f2'>N</div><div class='tweet-body'><div class='tweet-name'>{art['source'].split(' / ')[0]} <span class='tweet-verified' title='Cuenta verificada'>&#10004;</span></div><div class='tweet-handle'>@Noticias</div><p class='tweet-text'>{art['excerptEs'][:120]}...</p><div class='tweet-meta'>{art['date']} · <a href='{art['sourceUrl']}' target='_blank' rel='noopener noreferrer'>Ver fuente original</a></div></div></div>"
    expert = art.get('expertQuote', 'Las autoridades competentes brindaron declaraciones oficiales sobre el hecho.')
    expert_name = art.get('expertName', 'Autoridad oficial')
    expert_role = art.get('expertRole', 'Fuente oficial')
    ce += f"<div class='expert-quote'><div class='expert-avatar'></div><div class='expert-info'><strong>{expert_name}</strong><span>{expert_role}</span></div><blockquote>{expert}</blockquote></div>"
    ce += "<h2>Conclusión — Qué significa para la gente</h2>"
    ce += "<p>Para la ciudadanía, el dato clave es la continuidad del servicio y la ruta de reclamo: <strong>líneas oficiales</strong>, verificación en fuentes primarias y seguimiento mediático.</p>"

    en = f"<h1>{art['titleEn']}</h1>"
    en += f"<figure class='report-figure'><img src='{art['imageUrl']}' alt='{art['titleEn']}' loading='lazy'><figcaption>{art.get('imageCaption','Source: ' + art['source'])}</figcaption></figure>"
    en += f"<p><em>Introduction — {art['excerptEn']} This report rewrites and cross-checks official, TV and print sources with verification and diversity criteria.</em></p>"
    en += "<h2>Development — What happened and what sources say</h2>"
    en += f"<p>The event was first reported by <strong>{art['source'].split(' / ')[0]}</strong> and confirmed by <strong>{art['source']}</strong>.</p>"
    en += f"<div class='stat-grid'><div class='stat-card'><div class='stat-value'>{art['date'][5:]}</div><div class='stat-label'>Date</div></div><div class='stat-card'><div class='stat-value'>{art['date'][:4]}</div><div class='stat-label'>Year</div></div><div class='stat-card'><div class='stat-value'>{art['location'].split(',')[0]}</div><div class='stat-label'>Place</div></div><div class='stat-card'><div class='stat-value'>Verified</div><div class='stat-label'>Cross-checked</div></div></div>"
    en += f"<div class='tweet-card'><div class='tweet-avatar' style='background:#1da1f2'>N</div><div class='tweet-body'><div class='tweet-name'>{art['source'].split(' / ')[0]} <span class='tweet-verified' title='Verified'>&#10004;</span></div><div class='tweet-handle'>@Noticias</div><p class='tweet-text'>{art['excerptEn'][:120]}...</p><div class='tweet-meta'>{art['date']} · <a href='{art['sourceUrl']}' target='_blank' rel='noopener noreferrer'>View source</a></div></div></div>"
    en += f"<div class='expert-quote'><div class='expert-avatar'></div><div class='expert-info'><strong>{expert_name}</strong><span>{expert_role}</span></div><blockquote>{expert}</blockquote></div>"
    en += "<h2>Conclusion — What it means for people</h2>"
    en += "<p>For citizens, the key is service continuity and official channels: <strong>verified sources</strong>, primary data and media monitoring.</p>"

    cap = art.get('imageCaption', 'Fuente: ' + art['source'])
    lines = [
        "  {",
        f"    id: '{art['id']}',",
        "    contentType: 'news',",
        f"    slug: '{art['slug']}',",
        f"    titleEs: `{art['titleEs']}`,",
        f"    titleEn: `{art['titleEn']}`,",
        f"    excerptEs: `{art['excerptEs']}`,",
        f"    excerptEn: `{art['excerptEn']}`,",
        f"    contentEs: `{ce}`,",
        f"    contentEn: `{en}`,",
        f"    categoryEs: '{art['categoryEs']}',",
        f"    categoryEn: '{art['categoryEn']}',",
        f"    date: '{art['date']}',",
        f"    readTimeEs: '{art['readTimeEs']}',",
        f"    readTimeEn: '{art['readTimeEn']}',",
        f"    imageUrl: '{art['imageUrl']}',",
        f"    imageCaption: '{cap}',",
        f"    enableComments: {art.get('enableComments','true')},",
        f"    featured: {art.get('featured','false')},",
        f"    breaking: {art.get('breaking','false')},",
        "    views: 1,",
        f"    location: '{art['location']}',",
        f"    source: '{art['source']}',",
        f"    region: '{art['region']}',",
        f"    sourceUrl: '{art['sourceUrl']}'",
        "  },",
    ]
    return '\n'.join(lines)

articles = [
# NACIONALES
{"id":"1134","slug":"santa-cruz-comite-pro-abroga-ds-5676-plazo-domingo","titleEs":"Comité pro Santa Cruz da plazo al Gobierno hasta el domingo para abrogar el DS 5676","titleEn":"Santa Cruz Committee gives government until Sunday to repeal fuel decree DS 5676","excerptEs":"Stello Cochamanidis señaló que, si el Gobierno no retrocede hasta el domingo, el directorio analizará la solicitud del sector agropecuario para convocar a una Asamblea de la Cruceñidad.","excerptEn":"Stello Cochamanidis stated that if the government does not reverse course by Sunday, the board will analyze the agricultural sector's request to convene a Santa Cruz Assembly.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"6 min","readTimeEn":"6 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Manifestación en Santa Cruz contra el DS 5676. Fuente: El Deber.","enableComments":"true","featured":"true","breaking":"true","location":"Santa Cruz de la Sierra","source":"El Deber / Los Tiempos",    "region":"Bolivia","sourceUrl":"https://www.eldeber.com.bo","expertQuote":"Si el Gobierno no retrocede hasta el domingo, el directorio analizará la solicitud del sector agropecuario para convocar a una Asamblea de la Cruceñidad.","expertName":"Stello Cochamanidis","expertRole":"Presidente del Comité Pro Santa Cruz"},
{"id":"1135","slug":"cerimedo-palmasola-niega-poder-billetera-200-millones","titleEs":"Desde Palmasola, Cerimedo niega poder en el Gobierno y enfrenta allanamiento por $us 200 millones","titleEn":"From Palmasola, Cerimedo denies government power and faces raid over $200 million","excerptEs":"Fernando Cerimedo declaró desde la cárcel que 'su rol como colaborador del presidente no le otorgó ningún poder'. La Fiscalía allanó un departamento en Equipetrol y rastrea una billetera fría con $us 200 millones.","excerptEn":"Fernando Cerimedo declared from prison that 'his role as presidential collaborator did not grant him any power'. The Prosecutor's office raided an apartment in Equipetrol and is tracing a cold wallet with $200 million.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"7 min","readTimeEn":"7 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Fernando Cerimedo, asesor presidencial detenido. Fuente: Unitel.","enableComments":"true","featured":"true","breaking":"true","location":"La Paz / Santa Cruz","source":"Unitel / El Deber / Los Tiempos",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"Mi rol como colaborador del presidente no me otorgó ningún poder. Pronto la verdad saldrá a la luz.","expertName":"Fernando Cerimedo","expertRole":"Asesor presidencial detenido"},
{"id":"1136","slug":"paz-reconoce-ineficiencia-estado-respalda-velasco-diesel","titleEs":"Paz reconoce 'ineficiencia' del Estado y respalda propuesta de Velasco para importar diésel","titleEn":"Paz acknowledges state 'inefficiency' and backs Velasco's diesel import proposal","excerptEs":"El presidente admitió que 'el Estado es ineficiente, fuera del grado enorme de corrupción' y respaldó la propuesta del gobernador Velasco de importar diésel con privados.","excerptEn":"The president acknowledged that 'the state is inefficient' and backed Governor Velasco's proposal to import diesel with private operators.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"6 min","readTimeEn":"6 min","imageUrl":"/images/blog/bolivia-agosto-2026/rodrigo-paz-escasez-combustibles.jpg","imageCaption":"Presidente Rodrigo Paz reconoce ineficiencia estatal. Fuente: Unitel.","enableComments":"true","featured":"true","breaking":"false","location":"La Paz / Santa Cruz","source":"Unitel / Los Tiempos",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"El Estado es ineficiente, fuera del grado enorme de corrupción. El decreto se puede mejorar, pero no se puede retroceder.","expertName":"Rodrigo Paz Pereira","expertRole":"Presidente del Estado"},
{"id":"1137","slug":"paz-duplica-presupuesto-ypfb-subvencion-diesel-2027","titleEs":"Paz duplica el presupuesto de YPFB para subvencionar combustible hasta enero 2027","titleEn":"Paz doubles YPFB budget to subsidize fuel through January 2027","excerptEs":"El Gobierno duplicó el presupuesto de YPFB para mantener la subvención del combustible hasta enero del 2027. El dólar oficial sube a Bs 11,83 por cuarto día consecutivo.","excerptEn":"The government doubled YPFB's budget to maintain fuel subsidies through January 2027. The official dollar rises to Bs 11.83 for the fourth consecutive day.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Surtidor de combustible en La Paz. Fuente: Unitel.","enableComments":"true","featured":"false","breaking":"false","location":"La Paz","source":"Unitel",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"Si cambiamos el decreto o abrogamos, el resultado va a ser el mismo: no va a haber diésel.","expertName":"Juan Carlos Justiniano","expertRole":"Ministro de Hidrocarburos"},
{"id":"1138","slug":"puente-san-pablo-bloqueo-via-santa-cruz-beni","titleEs":"Reinstalan bloqueo en puente San Pablo tras gasificación; decenas de vehículos varados","titleEn":"Blockade reinstated at San Pablo bridge after tear gas; dozens stranded","excerptEs":"Productores de la provincia Marbán retomaron el bloqueo en el puente San Pablo tras la intervención policial-militar. La protesta, en su tercer día, exige la abrogación del DS 5676.","excerptEn":"Farmers from Marbán province reinstated the blockade at San Pablo bridge following police-military intervention. The protest, in its third day, demands repeal of DS 5676.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"6 min","readTimeEn":"6 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Bloqueo en el puente San Pablo, vía Santa Cruz-Beni. Fuente: Canal Rural.","enableComments":"true","featured":"false","breaking":"true","location":"San Pablo, Santa Cruz-Beni","source":"Canal Rural / Unitel / Red Uno",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"Los productores de la provincia Marbán no van a retroceder hasta que se abrogue el DS 5676.","expertName":"Líder campesino","expertRole":"Representante de productores"},
{"id":"1139","slug":"gobernacion-cruceña-decreto-importar-combustible","titleEs":"Gobernación cruceña alista decreto para importar combustible con privados","titleEn":"Santa Cruz governor's office drafts decree to import fuel with private operators","excerptEs":"La Gobernación de Santa Cruz prepara un decreto para habilitar la importación privada de combustible. JP Velasco promete 'inundar' la región con diésel en las próximas semanas.","excerptEn":"The Santa Cruz Governor's office is drafting a decree to enable private fuel imports. JP Velasco promises to 'flood' the region with diesel in the coming weeks.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Gobernación de Santa Cruz trabaja en decreto de importación. Fuente: El Deber.","enableComments":"true","featured":"false","breaking":"false","location":"Santa Cruz de la Sierra","source":"Unitel / El Deber / Los Tiempos",    "region":"Bolivia","sourceUrl":"https://www.eldeber.com.bo","expertQuote":"En las próximas semanas vamos a inundar a Santa Cruz de diésel y gasolina, con o sin permiso del Gobierno.","expertName":"JP Velasco","expertRole":"Gobernador de Santa Cruz"},
{"id":"1140","slug":"sokol-encargado-negocios-eeuu-bolivia","titleEs":"Sokol se reúne con el Encargado de Negocios de EEUU en Bolivia","titleEn":"Police commander Sokol meets with US Chargé d'Affaires in Bolivia","excerptEs":"Mirko Sokol, comandante de la Policía Boliviana, se reunió con Erik Martini. La Embajada calificó a Sokol como 'un verdadero luchador contra el crimen'.","excerptEn":"Mirko Sokol, commander of the Bolivian Police, met with Erik Martini. The Embassy described Sokol as 'a true fighter against crime'.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"4 min","readTimeEn":"4 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Sokol se reúne con Encargado de Negocios de EEUU. Fuente: Embajada de EEUU.","enableComments":"true","featured":"false","breaking":"false","location":"La Paz","source":"Unitel / El Deber",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"Sokol es un verdadero luchador contra el crimen.","expertName":"Erik Martini","expertRole":"Encargado de Negocios de EEUU en Bolivia"},
{"id":"1141","slug":"santa-cruz-fuertes-vientos-derribo-arboles","titleEs":"Fuertes vientos derriban árboles sobre vehículos en Santa Cruz y dejan un herido","titleEn":"Strong winds topple trees onto vehicles in Santa Cruz, injuring one","excerptEs":"Ráfagas de hasta 90 km/h azotaron Santa Cruz, derribando árboles sobre vehículos. Las brigadas evacuaron niños de una escuela. Bomberos combatieron incendios en Roboré.","excerptEn":"Gusts of up to 90 km/h hit Santa Cruz, toppling trees onto vehicles. Brigades evacuated children from a school. Firefighters fought fires in Roboré.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"4 min","readTimeEn":"4 min","imageUrl":"/images/blog/bolivia-agosto-2026/chiquitania-450-soldados-incendios.jpg","imageCaption":"Vientos fuertes en Santa Cruz. Fuente: El Deber.","enableComments":"true","featured":"false","breaking":"false","location":"Santa Cruz de la Sierra","source":"El Deber",    "region":"Bolivia","sourceUrl":"https://www.eldeber.com.bo","expertQuote":"Las ráfagas alcanzaron los 90 km/h y dejaron un herido.","expertName":"Bomberos de Santa Cruz","expertRole":"Cuerpo de Bomberos"},
{"id":"1142","slug":"eclipse-lunar-parcial-bolivia-luna-sangre","titleEs":"Eclipse lunar parcial: Bolivia vivió la 'Luna de Sangre' en evento excepcional","titleEn":"Partial lunar eclipse: Bolivia witnesses 'Blood Moon' in exceptional event","excerptEs":"El eclipse lunar parcial fue visible desde Bolivia desde las 22:33. La 'Luna de Sangre' cubrió el cielo boliviano. El fenómeno también se observó en Europa, África y Asia.","excerptEn":"The partial lunar eclipse was visible from Bolivia starting at 10:33 PM. The 'Blood Moon' covered the Bolivian sky. The phenomenon was also observed in Europe, Africa, and Asia.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg","imageCaption":"Eclipse lunar parcial visible en Bolivia. Fuente: Unitel / Los Tiempos.","enableComments":"true","featured":"false","breaking":"false","location":"Bolivia","source":"Unitel / Los Tiempos / Red Uno",    "region":"Bolivia","sourceUrl":"https://unitel.bo","expertQuote":"Agosto está siendo un mes extraordinario para los aficionados a la astronomía.","expertName":"Redacción Los Tiempos","expertRole":"Sección Ciencia"},
{"id":"1143","slug":"senado-aprueba-ley-acceso-informacion","titleEs":"Senado aprueba Ley de Acceso a la Información y la remite a Diputados","titleEn":"Senate approves Freedom of Information Act and sends it to Deputies","excerptEs":"La Cámara de Senadores aprobó el Proyecto de Ley de Acceso a la Información, que obligará al Estado a transparentar su información.","excerptEn":"The Senate approved the Freedom of Information Act, which will require the state to make its information transparent.","categoryEs":"Bolivia","categoryEn":"Bolivia","date":"2026-08-28","readTimeEs":"4 min","readTimeEn":"4 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Senado aprueba Ley de Acceso a la Información. Fuente: Los Tiempos.","enableComments":"true","featured":"false","breaking":"false","location":"Sucre / La Paz","source":"Los Tiempos / Red Uno",    "region":"Bolivia","sourceUrl":"https://www.lostiempos.com","expertQuote":"La transparencia no admite zonas grises. Este es un avance histórico.","expertName":"Pedro Rivero Jordán","expertRole":"Editorial El Deber"},
# INTERNACIONALES
{"id":"1144","slug":"nepal-riada-bhote-koshi-553-muertos","titleEs":"Nepal sube a 553 los muertos por la riada del Bhote Koshi; rescate en 'fase crítica'","titleEn":"Nepal death toll rises to 553 from Bhote Koshi flood; rescue in 'critical stage'","excerptEs":"La riada destructiva dejó 553 cadáveres hallados y al menos 1.400 desaparecidos. China advirtió del desbordamiento de un lago y suspendió labores de búsqueda.","excerptEn":"The destructive flash flood left 553 bodies recovered and at least 1,400 missing. China warned of a lake overflow and suspended search operations.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"7 min","readTimeEn":"7 min","imageUrl":"/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg","imageCaption":"Riada en Nepal destruye pueblos enteros. Fuente: Agencia EFE / BBC Mundo.","enableComments":"true","featured":"true","breaking":"true","location":"Katmandú, Nepal","source":"Agencia EFE / BBC Mundo","region":"International","sourceUrl":"https://efe.com","expertQuote":"Las autoridades nepalíes han alertado de que el nivel del río Bhote Koshi está subiendo.","expertName":"Gobierno de Nepal","expertRole":"Autoridad de emergencias"},
{"id":"1145","slug":"noruega-harald-v-muere-haakon-viii-rey","titleEs":"Muere Harald V de Noruega a los 89 años; Haakon VIII asume el trono","titleEn":"Norway's King Harald V dies at 89; Haakon VIII takes the throne","excerptEs":"La Casa Real confirmó el fallecimiento del rey Harald V 'plácidamente' en Oslo. Su hijo Haakon VIII asume la corona con el lema 'Todo por Noruega'.","excerptEn":"The Royal House confirmed King Harald V's 'peaceful' death in Oslo. His son Haakon VIII takes the throne with the motto 'All for Norway'.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"6 min","readTimeEn":"6 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Rey Harald V de Noruega (1937-2026). Fuente: Agencia EFE / RTVE.","enableComments":"true","featured":"true","breaking":"true","location":"Oslo, Noruega","source":"Agencia EFE / BBC Mundo / RTVE","region":"International","sourceUrl":"https://efe.com","expertQuote":"El rey Harald falleció plácidamente este viernes 28 de agosto.","expertName":"Casa Real de Noruega","expertRole":"Comunicado oficial"},
{"id":"1146","slug":"ceuta-krisis-migrantes-disturbios","titleEs":"España llama a la calma tras noche de protestas y disturbios en Ceuta","titleEn":"Spain calls for calm after night of protests and unrest in Ceuta","excerptEs":"El Gobierno cifró en 5.000 los migrantes en Ceuta frente a 20.000 del PP y Vox. Manifestantes destrozaron campamentos en la playa.","excerptEn":"The government estimated 5,000 migrants in Ceuta versus 20,000 from PP and Vox. Protesters destroyed beach camps.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"7 min","readTimeEn":"7 min","imageUrl":"/images/blog/bolivia-agosto-2026/sequia-26-municipios-emergencia.jpg","imageCaption":"Disturbios en Ceuta por crisis migratoria. Fuente: Agencia EFE / RTVE.","enableComments":"true","featured":"true","breaking":"false","location":"Ceuta, España","source":"Agencia EFE / RTVE","region":"International","sourceUrl":"https://efe.com","expertQuote":"Se adoptarán las medidas sancionadoras que correspondan con quienes cometan actos vandálicos.","expertName":"Fernando Grande-Marlaska","expertRole":"Ministro del Interior de España"},
{"id":"1147","slug":"espana-inflacion-43-agosto","titleEs":"Inflación en España se dispara al 4,3% en agosto, el más alto en 3 años","titleEn":"Spain's inflation surges to 4.3% in August, highest in 3 years","excerptEs":"El IPC español alcanzó el 4,3%, impulsado por el precio de los combustibles. La subida evidencia el impacto de la crisis energética.","excerptEn":"Spain's CPI reached 4.3%, driven by fuel prices. The increase highlights the impact of the energy crisis.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Inflación en España sube por combustibles. Fuente: RTVE.","enableComments":"true","featured":"false","breaking":"false","location":"Madrid, España","source":"RTVE / Agencia EFE","region":"International","sourceUrl":"https://www.rtve.es","expertQuote":"La inflación se dispara al 4,3%, el nivel más alto en más de tres años.","expertName":"Sofía Soler","expertRole":"Redactora RTVE"},
{"id":"1148","slug":"guerra-iran-eeuu-seis-meses","titleEs":"Seis meses de guerra en Irán: de la ofensiva sorpresa al enquistamiento","titleEn":"Six months of war in Iran: from surprise offensive to entrenched stalemate","excerptEs":"Un ataque inicial que acabó con la cúpula iraní dejó, a seis meses, un escenario de enquistamiento. EE.UU. e Irán no encuentran salida.","excerptEn":"An initial attack that took out Iran's leadership has left, six months later, an entrenched stalemate. The US and Iran cannot find a way out.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"8 min","readTimeEn":"8 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Guerra en Irán: seis meses de conflicto. Fuente: Agencia EFE / RTVE.","enableComments":"true","featured":"true","breaking":"false","location":"Teherán, Irán","source":"Agencia EFE / RTVE / BBC Mundo","region":"International","sourceUrl":"https://efe.com","expertQuote":"Un ataque inicial sorpresa que acabó con la cúpula iraní, semanas de bombardeos y meses de amenazas.","expertName":"Agencia EFE","expertRole":"Análisis internacional"},
{"id":"1149","slug":"trump-lago-ontario-lake-america","titleEs":"Trump firma orden para renombrar lago Ontario como 'Lake America'; Canadá rechaza","titleEn":"Trump signs order to rename Lake Ontario 'Lake America'; Canada rejects","excerptEs":"Trump firmó una orden ejecutiva para renombrar el lago Ontario como 'Lake America' en medio de la guerra comercial. Canadá rechazó el cambio.","excerptEn":"Trump signed an executive order to rename Lake Ontario as 'Lake America' amid the trade war. Canada rejected the change.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg","imageCaption":"Trump firma orden sobre lago Ontario. Fuente: BBC Mundo.","enableComments":"true","featured":"false","breaking":"false","location":"Washington, EE.UU.","source":"BBC Mundo / CNN en Español","region":"International","sourceUrl":"https://www.bbc.com","expertQuote":"Canadá rechazó el nuevo nombre del lago que comparten ambos países.","expertName":"Gobierno de Canadá","expertRole":"Comunicado oficial"},
{"id":"1150","slug":"meta-restricciones-menores-18-billon","titleEs":"Meta anuncia restricciones para menores tras acuerdo de $us 18.000 millones","titleEn":"Meta announces restrictions for minors after $18 billion settlement","excerptEs":"Como parte de un acuerdo de $us 18.000 millones por demandas de seguridad infantil, Meta anunció nuevas restricciones. Padres califican las medidas como 'no suficientes'.","excerptEn":"As part of an $18 billion child safety settlement, Meta announced new restrictions. Parents describe the measures as 'not far enough'.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"5 min","readTimeEn":"5 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"Meta nuevas restricciones para menores. Fuente: BBC Mundo.","enableComments":"true","featured":"false","breaking":"false","location":"California, EE.UU.","source":"BBC Mundo / CNN en Español","region":"International","sourceUrl":"https://www.bbc.com","expertQuote":"No es suficiente. Necesitamos protecciones más fuertes.","expertName":"Padres de familia","expertRole":"Familias afectadas"},
{"id":"1151","slug":"argelia-incendios-12-muertos","titleEs":"Incendios forestales en Argelia dejan 12 muertos; tres días de luto","titleEn":"Wildfires in Algeria leave 12 dead; three days of mourning","excerptEs":"Al menos 12 personas murieron en incendios forestales que azotaron Argelia. El presidente decretó tres días de luto nacional.","excerptEn":"At least 12 people died in wildfires sweeping Algeria. The president declared three days of national mourning.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"4 min","readTimeEn":"4 min","imageUrl":"/images/blog/bolivia-agosto-2026/chiquitania-450-soldados-incendios.jpg","imageCaption":"Incendios forestales en Argelia. Fuente: BBC Mundo.","enableComments":"true","featured":"false","breaking":"false","location":"Argel, Argelia","source":"BBC Mundo / Agencia EFE","region":"International","sourceUrl":"https://www.bbc.com","expertQuote":"Al menos 12 personas han muerto en los incendios forestales.","expertName":"BBC Mundo","expertRole":"Corresponsalía"},
{"id":"1152","slug":"gta-6-preview-oficial","titleEs":"Rockstar presenta vista oficial de GTA 6: fans y críticos impresionados","titleEn":"Rockstar unveils official GTA 6 preview: fans and critics impressed","excerptEs":"La vista oficial del videojuego más anticipado dejó satisfechos a fans y críticos. GTA 6 promete ser el título más ambicioso de la franquicia.","excerptEn":"The official look at the world's most anticipated video game left fans and critics impressed. GTA 6 promises to be the franchise's most ambitious title.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"4 min","readTimeEn":"4 min","imageUrl":"/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg","imageCaption":"GTA 6 preview oficial. Fuente: BBC Mundo.","enableComments":"true","featured":"false","breaking":"false","location":"New York, EE.UU.","source":"BBC Mundo","region":"International","sourceUrl":"https://www.bbc.com","expertQuote":"Lo que sabemos después de la gran vista previa de GTA 6.","expertName":"BBC Mundo","expertRole":"Sección Tecnología"},
{"id":"1153","slug":"migrantes-nepal-britanicos-desaparecidos","titleEs":"Familias vuelan a Nepal en busca de 33 británicos desaparecidos","titleEn":"Families fly to Nepal searching for 33 missing British nationals","excerptEs":"Entre los desaparecidos hay una niña de 13 años y un adolescente de 14. Las familias viajan a Nepal mientras el rescate se complica.","excerptEn":"Among the missing are a 13-year-old girl and a 14-year-old boy. Families travel to Nepal as rescue is complicated.","categoryEs":"Mundo","categoryEn":"World","date":"2026-08-28","readTimeEs":"6 min","readTimeEn":"6 min","imageUrl":"/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg","imageCaption":"Familias británicas buscan seres queridos en Nepal. Fuente: BBC Mundo.","enableComments":"true","featured":"false","breaking":"false","location":"Katmandú, Nepal","source":"BBC Mundo / Agencia EFE","region":"International","sourceUrl":"https://www.bbc.com","expertQuote":"Entre los nacionales británicos desaparecidos hay una niña de 13 años y un adolescente de 14.","expertName":"BBC Mundo","expertRole":"Corresponsalía en Nepal"}
]

# Read source
src = TS.read_text(encoding='utf-8')

# Replace each article
for art in articles:
    aid = art['id']
    new_block = make_article(art)
    pattern = re.compile(r"\{\s*\n    id: '%s',.*?\n  \}," % re.escape(aid), re.DOTALL)
    m = pattern.search(src)
    if m:
        old = m.group(0)
        src = src[:m.start()] + new_block + src[m.end():]
        print(f"replaced {aid} old={len(old)} new={len(new_block)}")
    else:
        print(f"NOT FOUND: {aid}")

TS.write_text(src, encoding='utf-8')
print("done")
