import pathlib, re

new_articles = [
# ===== 10 NOTICIAS NACIONALES =====
{
    "id": "1134",
    "contentType": "news",
    "slug": "santa-cruz-comite-pro-abroga-ds-5676-plazo-domingo",
    "titleEs": "Comité pro Santa Cruz da plazo al Gobierno hasta el domingo para abrogar el DS 5676",
    "titleEn": "Santa Cruz Committee gives government until Sunday to repeal fuel decree DS 5676",
    "excerptEs": "Stello Cochamanidis señaló que, si el Gobierno no retrocede hasta el domingo, el directorio analizará la solicitud del sector agropecuario para convocar a una Asamblea de la Cruceñidad.",
    "excerptEn": "Stello Cochamanidis stated that if the government does not reverse course by Sunday, the board will analyze the agricultural sector's request to convene a Santa Cruz Assembly.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 5,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": True,
    "views": 1,
    "location": "Santa Cruz de la Sierra",
    "source": "El Deber",
    "region": "National",
    "sourceUrl": "https://www.eldeber.com.bo"
},
{
    "id": "1135",
    "contentType": "news",
    "slug": "cerimedo-palmasola-niega-poder-allanamiento-equipetrol",
    "titleEs": "Desde Palmasola, Cerimedo niega poder en el Gobierno y enfrenta nuevos allanamientos",
    "titleEn": "From Palmasola prison, Cerimedo denies government power and faces new raids",
    "excerptEs": "Fernando Cerimedo, detenido por enriquecimiento ilícito y tentativa de feminicidio, declaró desde la cárcel que 'su rol como colaborador del presidente no le otorgó ningún poder'. La Fiscalía allanó un departamento en Equipetrol y rastrea una billetera fría con $us 200 millones.",
    "excerptEn": "Fernando Cerimedo, detained for illicit enrichment and attempted femicide, declared from prison that 'his role as presidential collaborator did not grant him any power'. The Prosecutor's office raided an apartment in Equipetrol and is tracing a cold wallet with $200 million.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 6,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": True,
    "views": 1,
    "location": "La Paz / Santa Cruz",
    "source": "Unitel / El Deber / Los Tiempos",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1136",
    "contentType": "news",
    "slug": "paz-reconoce-ineficiencia-estado-respalda-velasco-diesel",
    "titleEs": "Paz reconoce 'ineficiencia' del Estado y respalda propuesta de Velasco para importar diésel",
    "titleEn": "Paz acknowledges state 'inefficiency' and backs Velasco's diesel import proposal",
    "excerptEs": "El presidente Rodrigo Paz admitió que 'el Estado es ineficiente, fuera del grado enorme de corrupción' y respaldó la propuesta del gobernador cruceño JP Velasco de importar diésel con privados. El DS 5676, que fija el precio en Bs 128, es calificado como un 'condicionamiento' del FMI.",
    "excerptEn": "President Rodrigo Paz acknowledged that 'the state is inefficient, beyond the enormous level of corruption' and backed Santa Cruz Governor JP Velasco's proposal to import diesel with private operators. The DS 5676, setting the price at Bs 128, is characterized as an IMF 'condition'.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 5,
    "imageUrl": "/images/blog/bolivia-agosto-2026/rodrigo-paz-escasez-combustibles.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": False,
    "views": 1,
    "location": "La Paz / Santa Cruz",
    "source": "Unitel / Los Tiempos",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1137",
    "contentType": "news",
    "slug": "paz-duplica-presupuesto-ypfb-subvencion-diesel-2027",
    "titleEs": "Paz duplica el presupuesto de YPFB para subvencionar combustible hasta enero 2027",
    "titleEn": "Paz doubles YPFB budget to subsidize fuel through January 2027",
    "excerptEs": "El Gobierno duplicó el presupuesto de YPFB para mantener la subvención del combustible hasta enero del 2027, mientras las filas en surtidores se extienden a nivel nacional. El dólar oficial sube a Bs 11,83 por cuarto día consecutivo.",
    "excerptEn": "The government doubled YPFB's budget to maintain fuel subsidies through January 2027, while fuel station queues extend nationwide. The official dollar rises to Bs 11.83 for the fourth consecutive day.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "La Paz",
    "source": "Unitel",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1138",
    "contentType": "news",
    "slug": "puente-san-pablo-bloqueo-via-santa-cruz-beni",
    "titleEs": "Reinstalan bloqueo en puente San Pablo tras gasificación; decenas de vehículos varados",
    "titleEn": "Blockade reinstated at San Pablo bridge after tear gas; dozens of vehicles stranded",
    "excerptEs": "Productores de la provincia Marbán retomaron el bloqueo en el puente San Pablo, vía Santa Cruz-Beni, tras la intervención policial-militar con gas lacrimógeno. La protesta, en su tercer día, exige la abrogación del DS 5676 que eliminó la subvención al diésel.",
    "excerptEn": "Farmers from Marbán province reinstated the blockade at San Pablo bridge on the Santa Cruz-Beni road, following police-military intervention with tear gas. The protest, in its third day, demands repeal of DS 5676 which eliminated diesel subsidies.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 5,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": True,
    "views": 1,
    "location": "San Pablo, Santa Cruz-Beni",
    "source": "Canal Rural / Unitel / Red Uno",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1139",
    "contentType": "news",
    "slug": "gobernacion-cruceña-decreto-importar-combustible-privados",
    "titleEs": "Gobernación cruceña alista decreto para importar combustible con privados 'con o sin permiso'",
    "titleEn": "Santa Cruz governor's office drafts decree to import fuel with private operators",
    "excerptEs": "La Gobernación de Santa Cruz prepara un decreto para habilitar la importación privada de combustible, mientras JP Velasco promete 'inundar' la región con diésel y gasolina 'en las próximas semanas'. El acuerdo busca estabilizar el abastecimiento en 30 días.",
    "excerptEn": "The Santa Cruz Governor's office is drafting a decree to enable private fuel imports, while JP Velasco promises to 'flood' the region with diesel and gasoline 'in the coming weeks'. The agreement aims to stabilize supply within 30 days.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Santa Cruz de la Sierra",
    "source": "Unitel / El Deber / Los Tiempos",
    "region": "National",
    "sourceUrl": "https://www.eldeber.com.bo"
},
{
    "id": "1140",
    "contentType": "news",
    "slug": "sokol-encargado-negocios-eeuu-bolivia-reunion",
    "titleEs": "Sokol se reúne con el Encargado de Negocios de EEUU en Bolivia",
    "titleEn": "Police commander Sokol meets with US Chargé d'Affaires in Bolivia",
    "excerptEs": "Mirko Sokol, comandante de la Policía Boliviana, se reunió con Erik Martini, Encargado de Negocios de Estados Unidos en Bolivia. La Embajada de EEUU compartió una fotografía de la reunión y calificó a Sokol como 'un verdadero luchador contra el crimen'.",
    "excerptEn": "Mirko Sokol, commander of the Bolivian Police, met with Erik Martini, US Chargé d'Affaires in Bolivia. The US Embassy shared a photo of the meeting and described Sokol as 'a true fighter against crime'.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 3,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "La Paz",
    "source": "Unitel / El Deber",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1141",
    "contentType": "news",
    "slug": "santa-cruz-fuertes-vientos-derribo-arboles-herido",
    "titleEs": "Fuertes vientos derriban árboles sobre vehículos en Santa Cruz y dejan un herido",
    "titleEn": "Strong winds topple trees onto vehicles in Santa Cruz, injuring one person",
    "excerptEs": "Ráfagas de hasta 90 km/h azotaron Santa Cruz, derribando árboles sobre vehículos y dejando un herido. Las brigadas municipales evacuaron niños de una escuela. Bomberos se movilizaron para sofocar incendios en Roboré y San Matías.",
    "excerptEn": "Gusts of up to 90 km/h hit Santa Cruz, toppling trees onto vehicles and injuring one person. Municipal brigades evacuated children from a school. Firefighters were mobilized to extinguish fires in Roboré and San Matías.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/chiquitania-450-soldados-incendios.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Santa Cruz de la Sierra",
    "source": "El Deber",
    "region": "National",
    "sourceUrl": "https://www.eldeber.com.bo"
},
{
    "id": "1142",
    "contentType": "news",
    "slug": "eclipse-lunar-parcial-bolivia-luna-sangre-2026",
    "titleEs": "Eclipse lunar parcial: Bolivia vivió la 'Luna de Sangre' en un evento que tardará años en repetirse",
    "titleEn": "Partial lunar eclipse: Bolivia witnesses 'Blood Moon' in event that won't repeat for years",
    "excerptEs": "El eclipse lunar parcial fue visible desde Bolivia desde las 22:33 de la noche, con la 'Luna de Sangre' cubriendo el cielo boliviano. El fenómeno astronómico, que también se observó en Europa, África y Asia occidental, generó expectativa en redes sociales.",
    "excerptEn": "The partial lunar eclipse was visible from Bolivia starting at 10:33 PM, with the 'Blood Moon' covering the Bolivian sky. The astronomical phenomenon, also observed in Europe, Africa, and western Asia, generated excitement on social media.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Bolivia",
    "source": "Unitel / Los Tiempos / Red Uno",
    "region": "National",
    "sourceUrl": "https://unitel.bo"
},
{
    "id": "1143",
    "contentType": "news",
    "slug": "senado-aprueba-ley-acceso-informacion-remite-diputados",
    "titleEs": "Senado aprueba Ley de Acceso a la Información y la remite a Diputados para tratamiento",
    "titleEn": "Senate approves Freedom of Information Act and sends it to Chamber of Deputies",
    "excerptEs": "La Cámara de Senadores aprobó el Proyecto de Ley de Acceso a la Información, que obligará al Estado a transparentar su información. El proyecto fue remitido a la Cámara de Diputados para continuar su tratamiento legislativo.",
    "excerptEn": "The Senate approved the Freedom of Information Act, which will require the state to make its information transparent. The bill was sent to the Chamber of Deputies for further legislative process.",
    "categoryEs": "Bolivia",
    "categoryEn": "Bolivia",
    "date": "2026-08-28",
    "readTime": 3,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Sucre / La Paz",
    "source": "Los Tiempos / Red Uno",
    "region": "National",
    "sourceUrl": "https://www.lostiempos.com"
},
# ===== 10 NOTICIAS INTERNACIONALES =====
{
    "id": "1144",
    "contentType": "news",
    "slug": "nepal-riada-bhote-koshi-553-muertos-rescate-critico",
    "titleEs": "Nepal sube a 553 los muertos por la riada del Bhote Koshi; rescate llega a 'fase crítica'",
    "titleEn": "Nepal death toll rises to 553 from Bhote Koshi flood; rescue reaches 'critical stage'",
    "excerptEs": "La riada destructiva en la cuenca del Bhote Koshi dejó 553 cadáveres hallados y al menos 1.400 personas desaparecidas, incluyendo turistas extranjeros. China advirtió del desbordamiento de un lago formado por la avalancha y suspendió temporalmente las labores de búsqueda.",
    "excerptEn": "The destructive flash flood in the Bhote Koshi basin left 553 bodies recovered and at least 1,400 people missing, including foreign tourists. China warned of the imminent overflow of a lake formed by the avalanche and temporarily suspended search operations.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 6,
    "imageUrl": "/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": True,
    "views": 1,
    "location": "Katmandú, Nepal",
    "source": "Agencia EFE / BBC Mundo",
    "region": "International",
    "sourceUrl": "https://efe.com"
},
{
    "id": "1145",
    "contentType": "news",
    "slug": "noruega-harald-v-muere-haakon-viii-rey",
    "titleEs": "Muere Harald V de Noruega a los 89 años; Haakon VIII asume el trono",
    "titleEn": "Norway's King Harald V dies at 89; Haakon VIII takes the throne",
    "excerptEs": "La Casa Real de Noruega confirmó el fallecimiento del rey Harald V 'plácidamente' este viernes 28 de agosto en el Rikshospitalet de Oslo, donde estaba internado desde el 17 de agosto. Su hijo menor Haakon VIII asume la corona con el lema 'Todo por Noruega'.",
    "excerptEn": "Norway's Royal House confirmed the death of King Harald V 'peacefully' on Friday August 28 at Oslo's Rikshospitalet, where he had been hospitalized since August 17. His youngest son Haakon VIII takes the throne with the motto 'All for Norway'.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 5,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": True,
    "views": 1,
    "location": "Oslo, Noruega",
    "source": "Agencia EFE / BBC Mundo / RTVE",
    "region": "International",
    "sourceUrl": "https://efe.com"
},
{
    "id": "1146",
    "contentType": "news",
    "slug": "ceuta-krisis-migrantes-disturbios-espana",
    "titleEs": "España llama a la calma tras noche de protestas y disturbios en Ceuta por crisis migratoria",
    "titleEn": "Spain calls for calm after night of protests and unrest in Ceuta over migrant crisis",
    "excerptEs": "El Gobierno español cifró en 5.000 los migrantes aún en Ceuta frente a las cifras del PP y Vox de 20.000. Manifestantes destrozaron campamentos de migrantes en la playa y la Policía realizó disparos durante los disturbios. El comité de crisis reubicará a los migrantes.",
    "excerptEn": "The Spanish government estimated 5,000 migrants still in Ceuta versus PP and Vox figures of 20,000. Protesters destroyed migrant camps on the beach and police fired shots during unrest. The crisis committee will relocate migrants.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 6,
    "imageUrl": "/images/blog/bolivia-agosto-2026/sequia-26-municipios-emergencia.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": False,
    "views": 1,
    "location": "Ceuta, España",
    "source": "Agencia EFE / RTVE",
    "region": "International",
    "sourceUrl": "https://efe.com"
},
{
    "id": "1147",
    "contentType": "news",
    "slug": "espana-inflacion-43-agosto-combustibles",
    "titleEs": "La inflación en España se dispara al 4,3% en agosto por precio de combustibles, el más alto en 3 años",
    "titleEn": "Spain's inflation surges to 4.3% in August on fuel prices, highest in 3 years",
    "excerptEs": "El IPC español alcanzó el 4,3% en agosto, el nivel más alto en más de tres años, impulsado por el precio de los combustibles. La subida evidencia el impacto de la crisis energética en la economía doméstica española.",
    "excerptEn": "Spain's CPI reached 4.3% in August, the highest level in more than three years, driven by fuel prices. The increase highlights the impact of the energy crisis on the Spanish household economy.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Madrid, España",
    "source": "RTVE / Agencia EFE",
    "region": "International",
    "sourceUrl": "https://www.rtve.es"
},
{
    "id": "1148",
    "contentType": "news",
    "slug": "guerra-iran-eeuu-seis-meses-enquistamiento",
    "titleEs": "Seis meses de guerra en Irán: de la ofensiva sorpresa al enquistamiento sin salida",
    "titleEn": "Six months of war in Iran: from surprise offensive to entrenched stalemate",
    "excerptEs": "Un ataque inicial sorpresa que acabó con la cúpula iraní, semanas de bombardeos y meses de amenazas han dejado, a seis meses del comienzo de la guerra, un escenario de enquistamiento. EE.UU. e Irán no encuentran una salida al conflicto.",
    "excerptEn": "An initial surprise attack that took out Iran's leadership, weeks of bombings and months of threats have left, six months into the war, a scenario of entrenchment. The US and Iran cannot find a way out of the conflict.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 7,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": True,
    "breaking": False,
    "views": 1,
    "location": "Teherán, Irán",
    "source": "Agencia EFE / RTVE / BBC Mundo",
    "region": "International",
    "sourceUrl": "https://efe.com"
},
{
    "id": "1149",
    "contentType": "news",
    "slug": "trump-cambia-nombre-lago-ontario-lake-america",
    "titleEs": "Trump firma orden para cambiar nombre del lago Ontario a 'Lake America'; Canadá rechaza",
    "titleEn": "Trump signs order to rename Lake Ontario 'Lake America'; Canada rejects the change",
    "excerptEs": "El presidente Donald Trump firmó una orden ejecutiva para renombrar el lago Ontario como 'Lake America', en medio de la guerra comercial entre EE.UU. y Canadá. Canadá rechazó categóricamente el nuevo nombre del lago que comparten ambos países.",
    "excerptEn": "President Donald Trump signed an executive order to rename Lake Ontario as 'Lake America', amid the trade war between the US and Canada. Canada categorically rejected the new name of the lake shared by both countries.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/santa-cruz-importa-combustibles.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Washington, EE.UU.",
    "source": "BBC Mundo / CNN en Español",
    "region": "International",
    "sourceUrl": "https://www.bbc.com"
},
{
    "id": "1150",
    "contentType": "news",
    "slug": "meta-nuevas-restricciones-menores-18-billon-settlement",
    "titleEs": "Meta anuncia nuevas restricciones para menores en sus apps tras acuerdo de $us 18.000 millones",
    "titleEn": "Meta announces new restrictions for minors on its apps following $18 billion settlement",
    "excerptEs": "Como parte de un acuerdo de $us 18.000 millones por demandas de seguridad infantil, Meta anunció nuevas restricciones en sus aplicaciones para usuarios menores. Padres y adolescentes calificaron las medidas como 'no suficientes'.",
    "excerptEn": "As part of an $18 billion settlement over child safety lawsuits, Meta announced new restrictions on its apps for minor users. Parents and teens described the measures as 'not far enough'.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 4,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "California, EE.UU.",
    "source": "BBC Mundo / CNN en Español",
    "region": "International",
    "sourceUrl": "https://www.bbc.com"
},
{
    "id": "1151",
    "contentType": "news",
    "slug": "argelia-incendios-forestales-12-muertos-luto",
    "titleEs": "Incendios forestales en Argelia dejan al menos 12 muertos; el presidente decreta tres días de luto",
    "titleEn": "Wildfires in Algeria leave at least 12 dead; president declares three days of mourning",
    "excerptEs": "Al menos 12 personas han muerto en los incendios forestales que azotan Argelia durante la noche. El presidente del país decretó tres días de luto nacional por las víctimas del desastre.",
    "excerptEn": "At least 12 people have died in wildfires sweeping Algeria overnight. The country's president declared three days of national mourning for the disaster's victims.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 3,
    "imageUrl": "/images/blog/bolivia-agosto-2026/chiquitania-450-soldados-incendios.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Argel, Argelia",
    "source": "BBC Mundo / Agencia EFE",
    "region": "International",
    "sourceUrl": "https://www.bbc.com"
},
{
    "id": "1152",
    "contentType": "news",
    "slug": "gta-6-preview-oficial-fans-criticos",
    "titleEs": "Rockstar presenta la vista oficial de GTA 6: fans y críticos quedan impresionados",
    "titleEn": "Rockstar unveils official GTA 6 preview: fans and critics impressed",
    "excerptEs": "La vista oficial del videojuego más anticipado del mundo dejó satisfechos a fans y críticos. Grand Theft Auto 6 promete ser el título más ambicioso de la franquicia, con gráficos y un mundo abierto sin precedentes.",
    "excerptEn": "The official look at the world's most anticipated video game left fans and critics impressed. Grand Theft Auto 6 promises to be the most ambitious title in the franchise, with unprecedented graphics and open world.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 3,
    "imageUrl": "/images/blog/bolivia-agosto-2026/evo-morales-ordenes-captura.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "New York, EE.UU.",
    "source": "BBC Mundo",
    "region": "International",
    "sourceUrl": "https://www.bbc.com"
},
{
    "id": "1153",
    "contentType": "news",
    "slug": "migrantes-nepal-familias-britanicos-desaparecidos",
    "titleEs": "Familias vuelan a Nepal en busca de 33 nacionales británicos desaparecidos en la riada",
    "titleEn": "Families fly to Nepal searching for 33 missing British nationals in the flood",
    "excerptEs": "Entre los nacionales británicos reportados desaparecidos hay una niña de 13 años y un adolescente de 14. Las familias viajan a Nepal mientras las labores de rescate se complican por el riesgo de un nuevo desbordamiento.",
    "excerptEn": "Among the British nationals reported missing are a 13-year-old girl and a 14-year-old boy. Families are traveling to Nepal as rescue operations are complicated by the risk of a new overflow.",
    "categoryEs": "Mundo",
    "categoryEn": "World",
    "date": "2026-08-28",
    "readTime": 5,
    "imageUrl": "/images/blog/bolivia-agosto-2026/nevadas-potosi-frontera-chile.jpg",
    "enableComments": True,
    "featured": False,
    "breaking": False,
    "views": 1,
    "location": "Katmandú, Nepal",
    "source": "BBC Mundo / Agencia EFE",
    "region": "International",
    "sourceUrl": "https://www.bbc.com"
}
]

p = pathlib.Path('src/translations.ts')
content = p.read_text(encoding='utf-8')

# Remove old articles 1134-1153 by finding their blocks
for art in new_articles:
    # Remove existing article with same id if present
    pattern = r"\{\s*\n\s*id:\s*'" + art['id'] + r"'.*?\n\s*\},"
    content = re.sub(pattern, '', content, flags=re.DOTALL)

# Build new article blocks
blocks = []
for art in new_articles:
    block = f"""  {{
    id: '{art['id']}',
    contentType: '{art['contentType']}',
    slug: '{art['slug']}',
    titleEs: `{art['titleEs']}`,
    titleEn: `{art['titleEn']}`,
    excerptEs: `{art['excerptEs']}`,
    excerptEn: `{art['excerptEn']}`,
    categoryEs: '{art['categoryEs']}',
    categoryEn: '{art['categoryEn']}',
    date: '{art['date']}',
    readTime: {art['readTime']},
    imageUrl: '{art['imageUrl']}',
    enableComments: {str(art['enableComments'])},
    featured: {str(art['featured'])},
    breaking: {str(art['breaking'])},
    views: {art['views']},
    location: '{art['location']}',
    source: '{art['source']}',
    region: '{art['region']}',
    sourceUrl: '{art['sourceUrl']}'
  }}"""
    blocks.append(block)

new_section = '\n'.join(blocks)

# Insert before FIN DE NOTICIAS
content = content.replace('// FIN DE NOTICIAS', new_section + '\n// FIN DE NOTICIAS')

# Clean up multiple blank lines
content = re.sub(r'\n{3,}', '\n\n', content)

p.write_text(content, encoding='utf-8')
print(f"Done: inserted {len(new_articles)} articles")
